### ISSUE TITLE
dva-ast api design

### ISSUE THREAD

**Issue by ChrisFan** [dvajs/dva-ast#1]
>  core apis, the idea is to offers the abilities of get infrastructure data from the source code and write back after you updated these data.

### require('dav-ast').parse
```javascript
require('dav-ast').parse(
  [path],
  {options}
)
```

return an object which describes the dva infrastructure about your app,
```javascript
{
  $$node: <XNode>,
  models: [
    {
      $$node: <XNode>,
      namespace: 'user',
      state: {
        list: [],
        loading: false,
        total: null,
      },
      subscriptions: [
        'function (dispatch) {\n...',
      ],
      effects: {
        'users/query': 'function ...',
        'users/delete': '...'
        'users/create': '...',
        'users/update': '...',
      },
      reducers: {
        ...
      },
    }
  ],
  containers: [
    ...,
  ],
}
```

### XNode.save
```javascript
const userModel = ...;
delete userModel.effects['users/query'];
userModel.save();
```

update the source file.

**Comment by ChrisFan** [comment]
@sorrycc 基本的功能看下够了没

**Comment by sorrycc** [comment]
- 这是 model 部分的，其他的呢? router 和 component 的部分会考虑在内吗? 
- effects 和 subscriptions 是否应该分析出他们 put/dispatch 的 action?

**Comment by ChrisFan** [comment]
- component 部分我目前叫 containers，可以改个名字。router 后续会补上
- effects subscriptions 这块的 action 可以加上

比较纠结的一点是比如 subscriptions 解析出来的数据放在哪里，可能会变成：

```javascript
subscriptions: [
     <Subscription instance>
 ],
```
这样的话结构应该是 
```
models: [<Model instance>]
```

稍微复杂一些，不过更灵活些。
