### ISSUE TITLE
reducer and effect enhancement

### ISSUE THREAD

**Issue by jaredleechn** [dvajs/dva-ast#34]
```
reducerByIds: [{
  namespace,
  name,
}]
```

这里 namespace 就是 model 的 namespace，name 就是 effect 的 action type

这个是放在 selector 里面处理好一些还是放在 dva-ast 处理好？

**Comment by sorrycc** [comment]
结论?

**Comment by jaredleechn** [comment]
我看到代码里面通过 selector 来做了，reducer 上面存 modelId，根据 modelByIds 找到 model，再找到所有的 namespace
