### ISSUE TITLE
TypeError: root.findRouters(...).getRouterInfo is not a function

### ISSUE THREAD

**Issue by wenris** [dvajs/dva-ast#39]
When **jscodeshift** upgrades to `v0.3.32` , the following call would cause bugs:

```js
Collection.fromPaths([], this);
```

Please check it!

See: https://github.com/dvajs/dva-cli/issues/91

**Comment by wenris** [comment]
我已经找出 Bug 了，原因是新版 **jscodeshift** 使用的 `Collection` 的位置发生了变化，从 `'jscodeshift/dist/Collection';` 变为了 `'jscodeshift/src/Collection';` 。

涉事的三个文件如下：

1. dva-ast/lib/collections/Entry.js
2. dva-ast/lib/collections/RouteComponent.js
3. dva-ast/lib/collections/Router.js

**Comment by sorrycc** [comment]
dva-ast@0.3.5
